language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: stable
      name: "no_std stable"
      install:
        - rustup target add thumbv6m-none-eabi
      script:
        - cargo build --target thumbv6m-none-eabi --verbose
    - rust: nightly
      name: "nightly all features"
      script:
        - cargo build --all-features
    - rust: nightly
      name: "Miri"
      script:
        - ci/miri.sh
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
